# Generated by Django 2.1.1 on 2018-09-27 03:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='佚名', max_length=20, verbose_name='姓名')),
                ('comment', models.TextField(max_length=100, verbose_name='评论')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 9, 27, 3, 13, 0, 46136, tzinfo=utc), verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '博客评论',
                'verbose_name_plural': '博客评论',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 3, 13, 0, 44137, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Blog', verbose_name='博客'),
        ),
    ]
